server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE

#Below Configuration will be fetched from github by cloud-config server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost