server:
  port: 9002


spring:
  application:
    name: USER-SERVICE

#Below Configuration will be fetched from Github Using the Cloud-Config-Server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost